export type FdsToken = { name: "fds-size-1", value: "8px" } | { name: "fds-size-2", value: "16px" } | { name: "fds-size-3", value: "24px" } | { name: "fds-size-4", value: "32px" } | { name: "fds-size-6", value: "48px" } | { name: "fds-size-8", value: "64px" } | { name: "fds-size-12", value: "96px" } | { name: "fds-size-16", value: "128px" } | { name: "fds-size-24", value: "192px" } | { name: "fds-size-32", value: "256px" } | { name: "fds-radius-compact", value: "2px" } | { name: "fds-radius-normal", value: "4px" } | { name: "fds-radius-large", value: "8px" } | { name: "fds-radius-rounded", value: "1000px" } | { name: "fds-style-elevation-100", value: "0px 1px 2px 0px rgba(0, 0, 0, 0.24), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)" } | { name: "fds-style-elevation-200", value: "0px 6px 6px 0px rgba(0, 0, 0, 0.23), 0px 3px 6px 0px rgba(0, 0, 0, 0.16)" } | { name: "fds-style-elevation-300", value: "0px 6px 12px 0px rgba(0, 0, 0, 0.23), 0px 20px 20px 0px rgba(0, 0, 0, 0.19)" } | { name: "fds-style-elevation-400", value: "0px 20px 20px 0px rgba(0, 0, 0, 0.22), 0px 50px 100px 0px rgba(0, 0, 0, 0.25)" } | { name: "fds-typography-body-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-default-font-size", value: "16px" } | { name: "fds-typography-body-default-letter-spacing", value: "0px" } | { name: "fds-typography-body-default-line-height", value: "150%" } | { name: "fds-typography-body-default-font-weight", value: "400" } | { name: "fds-typography-body-default-display", value: "inline-block" } | { name: "fds-typography-body-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-large-font-size", value: "18px" } | { name: "fds-typography-body-large-letter-spacing", value: "0px" } | { name: "fds-typography-body-large-line-height", value: "150%" } | { name: "fds-typography-body-large-font-weight", value: "400" } | { name: "fds-typography-body-large-display", value: "inline-block" } | { name: "fds-typography-body-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-micro-font-size", value: "12px" } | { name: "fds-typography-body-micro-letter-spacing", value: "0px" } | { name: "fds-typography-body-micro-line-height", value: "150%" } | { name: "fds-typography-body-micro-font-weight", value: "400" } | { name: "fds-typography-body-micro-display", value: "inline-block" } | { name: "fds-typography-body-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-small-font-size", value: "14px" } | { name: "fds-typography-body-small-letter-spacing", value: "0px" } | { name: "fds-typography-body-small-line-height", value: "150%" } | { name: "fds-typography-body-small-font-weight", value: "400" } | { name: "fds-typography-body-small-display", value: "inline-block" } | { name: "fds-typography-emphasis-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-default-font-size", value: "16px" } | { name: "fds-typography-emphasis-default-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-default-line-height", value: "150%" } | { name: "fds-typography-emphasis-default-font-weight", value: "700" } | { name: "fds-typography-emphasis-default-display", value: "inline-block" } | { name: "fds-typography-emphasis-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-large-font-size", value: "18px" } | { name: "fds-typography-emphasis-large-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-large-line-height", value: "150%" } | { name: "fds-typography-emphasis-large-font-weight", value: "700" } | { name: "fds-typography-emphasis-large-display", value: "inline-block" } | { name: "fds-typography-emphasis-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-micro-font-size", value: "12px" } | { name: "fds-typography-emphasis-micro-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-micro-line-height", value: "150%" } | { name: "fds-typography-emphasis-micro-font-weight", value: "700" } | { name: "fds-typography-emphasis-micro-display", value: "inline-block" } | { name: "fds-typography-emphasis-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-small-font-size", value: "14px" } | { name: "fds-typography-emphasis-small-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-small-line-height", value: "150%" } | { name: "fds-typography-emphasis-small-font-weight", value: "700" } | { name: "fds-typography-emphasis-small-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-3-font-size", value: "40px" } | { name: "fds-typography-heading-large-heading-3-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-3-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-3-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-3-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-4-font-size", value: "32px" } | { name: "fds-typography-heading-large-heading-4-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-4-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-4-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-4-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-5-font-size", value: "28px" } | { name: "fds-typography-heading-large-heading-5-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-5-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-5-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-5-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-6-font-size", value: "20px" } | { name: "fds-typography-heading-large-heading-6-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-6-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-6-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-6-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-1-font-size", value: "64px" } | { name: "fds-typography-heading-large-heading-1-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-1-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-1-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-1-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-2-font-size", value: "48px" } | { name: "fds-typography-heading-large-heading-2-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-2-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-2-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-2-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-1-font-size", value: "42px" } | { name: "fds-typography-heading-small-heading-1-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-1-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-1-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-1-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-2-font-size", value: "32px" } | { name: "fds-typography-heading-small-heading-2-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-2-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-2-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-2-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-3-font-size", value: "28px" } | { name: "fds-typography-heading-small-heading-3-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-3-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-3-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-3-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-4-font-size", value: "24px" } | { name: "fds-typography-heading-small-heading-4-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-4-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-4-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-4-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-5-font-size", value: "18px" } | { name: "fds-typography-heading-small-heading-5-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-5-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-5-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-5-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-6-font-size", value: "16px" } | { name: "fds-typography-heading-small-heading-6-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-6-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-6-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-6-display", value: "inline-block" } | { name: "fds-typography-link-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-large-font-size", value: "18px" } | { name: "fds-typography-link-large-letter-spacing", value: "0px" } | { name: "fds-typography-link-large-line-height", value: "150%" } | { name: "fds-typography-link-large-font-weight", value: "400" } | { name: "fds-typography-link-large-text-decoration", value: "underline" } | { name: "fds-typography-link-large-display", value: "inline-block" } | { name: "fds-typography-link-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-micro-font-size", value: "12px" } | { name: "fds-typography-link-micro-letter-spacing", value: "0px" } | { name: "fds-typography-link-micro-line-height", value: "150%" } | { name: "fds-typography-link-micro-font-weight", value: "400" } | { name: "fds-typography-link-micro-text-decoration", value: "underline" } | { name: "fds-typography-link-micro-display", value: "inline-block" } | { name: "fds-typography-link-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-small-font-size", value: "14px" } | { name: "fds-typography-link-small-letter-spacing", value: "0px" } | { name: "fds-typography-link-small-line-height", value: "150%" } | { name: "fds-typography-link-small-font-weight", value: "400" } | { name: "fds-typography-link-small-text-decoration", value: "underline" } | { name: "fds-typography-link-small-display", value: "inline-block" } | { name: "fds-typography-link-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-default-font-size", value: "16px" } | { name: "fds-typography-link-default-letter-spacing", value: "0px" } | { name: "fds-typography-link-default-line-height", value: "150%" } | { name: "fds-typography-link-default-font-weight", value: "400" } | { name: "fds-typography-link-default-text-decoration", value: "underline" } | { name: "fds-typography-link-default-display", value: "inline-block" } | { name: "fds-typography-ui-helper-font-family", value: "'Public Sans', 'PublicSans-Regular'" } | { name: "fds-typography-ui-helper-font-size", value: "15px" } | { name: "fds-typography-ui-helper-letter-spacing", value: "0px" } | { name: "fds-typography-ui-helper-line-height", value: "100%" } | { name: "fds-typography-ui-helper-font-weight", value: "400" } | { name: "fds-typography-ui-helper-display", value: "inline-block" } | { name: "fds-typography-ui-id-font-family", value: "'Roboto Mono'" } | { name: "fds-typography-ui-id-font-size", value: "13px" } | { name: "fds-typography-ui-id-letter-spacing", value: "0px" } | { name: "fds-typography-ui-id-line-height", value: "100%" } | { name: "fds-typography-ui-id-font-weight", value: "700" } | { name: "fds-typography-ui-id-display", value: "inline-block" } | { name: "fds-typography-ui-label-font-family", value: "'Public Sans', 'PublicSans-Medium'" } | { name: "fds-typography-ui-label-font-size", value: "16px" } | { name: "fds-typography-ui-label-letter-spacing", value: "0px" } | { name: "fds-typography-ui-label-line-height", value: "22px" } | { name: "fds-typography-ui-label-font-weight", value: "500" } | { name: "fds-typography-ui-label-display", value: "inline-block" } | { name: "fds-typography-ui-placeholder-font-family", value: "'Public Sans', 'PublicSans-Medium'" } | { name: "fds-typography-ui-placeholder-font-size", value: "16px" } | { name: "fds-typography-ui-placeholder-letter-spacing", value: "0px" } | { name: "fds-typography-ui-placeholder-line-height", value: "100%" } | { name: "fds-typography-ui-placeholder-font-weight", value: "500" } | { name: "fds-typography-ui-placeholder-display", value: "inline-block" } | { name: "fds-typography-ui-tag-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-ui-tag-font-size", value: "16px" } | { name: "fds-typography-ui-tag-letter-spacing", value: "0px" } | { name: "fds-typography-ui-tag-line-height", value: "100%" } | { name: "fds-typography-ui-tag-font-weight", value: "700" } | { name: "fds-typography-ui-tag-display", value: "inline-block" } | { name: "fds-color-brand-black", value: "#000000" } | { name: "fds-color-brand-white", value: "#ffffff" } | { name: "fds-color-danger-50", value: "#FFF0ED" } | { name: "fds-color-danger-100", value: "#ff9b87" } | { name: "fds-color-danger-200", value: "#e55636" } | { name: "fds-color-danger-300", value: "#b40000" } | { name: "fds-color-danger-400", value: "#720000" } | { name: "fds-color-interactive-50", value: "#EFF8FF" } | { name: "fds-color-interactive-100", value: "#90cefe" } | { name: "fds-color-interactive-200", value: "#1777f8" } | { name: "fds-color-interactive-300", value: "#0034ac" } | { name: "fds-color-interactive-400", value: "#001c5b" } | { name: "fds-color-neutral-50", value: "#F6F6F6" } | { name: "fds-color-neutral-100", value: "#cdcdd7" } | { name: "fds-color-neutral-200", value: "#9696aa" } | { name: "fds-color-neutral-300", value: "#505064" } | { name: "fds-color-neutral-400", value: "#2c2c44" } | { name: "fds-color-success-50", value: "#EAFFF8" } | { name: "fds-color-success-100", value: "#82e8c3" } | { name: "fds-color-success-200", value: "#25a794" } | { name: "fds-color-success-300", value: "#005f61" } | { name: "fds-color-success-400", value: "#004042" } | { name: "fds-color-text-1", value: "#ffffff" } | { name: "fds-color-text-300", value: "#9696aa" } | { name: "fds-color-text-600", value: "#505064" } | { name: "fds-color-text-1000", value: "#000000" } | { name: "fds-color-warning-50", value: "#FFFADB" } | { name: "fds-color-warning-100", value: "#ffe37f" } | { name: "fds-color-warning-200", value: "#eec200" } | { name: "fds-color-warning-300", value: "#b47324" } | { name: "fds-color-warning-400", value: "#6c3e05" }
export type FdsColorToken = { name: "fds-color-brand-black", value: "#000000" } | { name: "fds-color-brand-white", value: "#ffffff" } | { name: "fds-color-danger-50", value: "#FFF0ED" } | { name: "fds-color-danger-100", value: "#ff9b87" } | { name: "fds-color-danger-200", value: "#e55636" } | { name: "fds-color-danger-300", value: "#b40000" } | { name: "fds-color-danger-400", value: "#720000" } | { name: "fds-color-interactive-50", value: "#EFF8FF" } | { name: "fds-color-interactive-100", value: "#90cefe" } | { name: "fds-color-interactive-200", value: "#1777f8" } | { name: "fds-color-interactive-300", value: "#0034ac" } | { name: "fds-color-interactive-400", value: "#001c5b" } | { name: "fds-color-neutral-50", value: "#F6F6F6" } | { name: "fds-color-neutral-100", value: "#cdcdd7" } | { name: "fds-color-neutral-200", value: "#9696aa" } | { name: "fds-color-neutral-300", value: "#505064" } | { name: "fds-color-neutral-400", value: "#2c2c44" } | { name: "fds-color-success-50", value: "#EAFFF8" } | { name: "fds-color-success-100", value: "#82e8c3" } | { name: "fds-color-success-200", value: "#25a794" } | { name: "fds-color-success-300", value: "#005f61" } | { name: "fds-color-success-400", value: "#004042" } | { name: "fds-color-text-1", value: "#ffffff" } | { name: "fds-color-text-300", value: "#9696aa" } | { name: "fds-color-text-600", value: "#505064" } | { name: "fds-color-text-1000", value: "#000000" } | { name: "fds-color-warning-50", value: "#FFFADB" } | { name: "fds-color-warning-100", value: "#ffe37f" } | { name: "fds-color-warning-200", value: "#eec200" } | { name: "fds-color-warning-300", value: "#b47324" } | { name: "fds-color-warning-400", value: "#6c3e05" }
export type FdsSizeToken = { name: "fds-size-1", value: "8px" } | { name: "fds-size-2", value: "16px" } | { name: "fds-size-3", value: "24px" } | { name: "fds-size-4", value: "32px" } | { name: "fds-size-6", value: "48px" } | { name: "fds-size-8", value: "64px" } | { name: "fds-size-12", value: "96px" } | { name: "fds-size-16", value: "128px" } | { name: "fds-size-24", value: "192px" } | { name: "fds-size-32", value: "256px" }
export const FdsTokenSize1: FdsSizeToken
export const FdsTokenSize2: FdsSizeToken
export const FdsTokenSize3: FdsSizeToken
export const FdsTokenSize4: FdsSizeToken
export const FdsTokenSize6: FdsSizeToken
export const FdsTokenSize8: FdsSizeToken
export const FdsTokenSize12: FdsSizeToken
export const FdsTokenSize16: FdsSizeToken
export const FdsTokenSize24: FdsSizeToken
export const FdsTokenSize32: FdsSizeToken
export const FdsTokenRadiusCompact: FdsToken
export const FdsTokenRadiusNormal: FdsToken
export const FdsTokenRadiusLarge: FdsToken
export const FdsTokenRadiusRounded: FdsToken
export const FdsTokenStyleElevation100: FdsToken
export const FdsTokenStyleElevation200: FdsToken
export const FdsTokenStyleElevation300: FdsToken
export const FdsTokenStyleElevation400: FdsToken
export const FdsTokenTypographyBodyDefaultFontFamily: FdsToken
export const FdsTokenTypographyBodyDefaultFontSize: FdsToken
export const FdsTokenTypographyBodyDefaultLetterSpacing: FdsToken
export const FdsTokenTypographyBodyDefaultLineHeight: FdsToken
export const FdsTokenTypographyBodyDefaultFontWeight: FdsToken
export const FdsTokenTypographyBodyDefaultDisplay: FdsToken
export const FdsTokenTypographyBodyLargeFontFamily: FdsToken
export const FdsTokenTypographyBodyLargeFontSize: FdsToken
export const FdsTokenTypographyBodyLargeLetterSpacing: FdsToken
export const FdsTokenTypographyBodyLargeLineHeight: FdsToken
export const FdsTokenTypographyBodyLargeFontWeight: FdsToken
export const FdsTokenTypographyBodyLargeDisplay: FdsToken
export const FdsTokenTypographyBodyMicroFontFamily: FdsToken
export const FdsTokenTypographyBodyMicroFontSize: FdsToken
export const FdsTokenTypographyBodyMicroLetterSpacing: FdsToken
export const FdsTokenTypographyBodyMicroLineHeight: FdsToken
export const FdsTokenTypographyBodyMicroFontWeight: FdsToken
export const FdsTokenTypographyBodyMicroDisplay: FdsToken
export const FdsTokenTypographyBodySmallFontFamily: FdsToken
export const FdsTokenTypographyBodySmallFontSize: FdsToken
export const FdsTokenTypographyBodySmallLetterSpacing: FdsToken
export const FdsTokenTypographyBodySmallLineHeight: FdsToken
export const FdsTokenTypographyBodySmallFontWeight: FdsToken
export const FdsTokenTypographyBodySmallDisplay: FdsToken
export const FdsTokenTypographyEmphasisDefaultFontFamily: FdsToken
export const FdsTokenTypographyEmphasisDefaultFontSize: FdsToken
export const FdsTokenTypographyEmphasisDefaultLetterSpacing: FdsToken
export const FdsTokenTypographyEmphasisDefaultLineHeight: FdsToken
export const FdsTokenTypographyEmphasisDefaultFontWeight: FdsToken
export const FdsTokenTypographyEmphasisDefaultDisplay: FdsToken
export const FdsTokenTypographyEmphasisLargeFontFamily: FdsToken
export const FdsTokenTypographyEmphasisLargeFontSize: FdsToken
export const FdsTokenTypographyEmphasisLargeLetterSpacing: FdsToken
export const FdsTokenTypographyEmphasisLargeLineHeight: FdsToken
export const FdsTokenTypographyEmphasisLargeFontWeight: FdsToken
export const FdsTokenTypographyEmphasisLargeDisplay: FdsToken
export const FdsTokenTypographyEmphasisMicroFontFamily: FdsToken
export const FdsTokenTypographyEmphasisMicroFontSize: FdsToken
export const FdsTokenTypographyEmphasisMicroLetterSpacing: FdsToken
export const FdsTokenTypographyEmphasisMicroLineHeight: FdsToken
export const FdsTokenTypographyEmphasisMicroFontWeight: FdsToken
export const FdsTokenTypographyEmphasisMicroDisplay: FdsToken
export const FdsTokenTypographyEmphasisSmallFontFamily: FdsToken
export const FdsTokenTypographyEmphasisSmallFontSize: FdsToken
export const FdsTokenTypographyEmphasisSmallLetterSpacing: FdsToken
export const FdsTokenTypographyEmphasisSmallLineHeight: FdsToken
export const FdsTokenTypographyEmphasisSmallFontWeight: FdsToken
export const FdsTokenTypographyEmphasisSmallDisplay: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading3Display: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading4Display: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading5Display: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading6Display: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading1Display: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2FontFamily: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2FontSize: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2LineHeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2FontWeight: FdsToken
export const FdsTokenTypographyHeadingLargeHeading2Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading1Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading2Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading3Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading4Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading5Display: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6FontFamily: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6FontSize: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6LetterSpacing: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6LineHeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6FontWeight: FdsToken
export const FdsTokenTypographyHeadingSmallHeading6Display: FdsToken
export const FdsTokenTypographyLinkLargeFontFamily: FdsToken
export const FdsTokenTypographyLinkLargeFontSize: FdsToken
export const FdsTokenTypographyLinkLargeLetterSpacing: FdsToken
export const FdsTokenTypographyLinkLargeLineHeight: FdsToken
export const FdsTokenTypographyLinkLargeFontWeight: FdsToken
export const FdsTokenTypographyLinkLargeTextDecoration: FdsToken
export const FdsTokenTypographyLinkLargeDisplay: FdsToken
export const FdsTokenTypographyLinkMicroFontFamily: FdsToken
export const FdsTokenTypographyLinkMicroFontSize: FdsToken
export const FdsTokenTypographyLinkMicroLetterSpacing: FdsToken
export const FdsTokenTypographyLinkMicroLineHeight: FdsToken
export const FdsTokenTypographyLinkMicroFontWeight: FdsToken
export const FdsTokenTypographyLinkMicroTextDecoration: FdsToken
export const FdsTokenTypographyLinkMicroDisplay: FdsToken
export const FdsTokenTypographyLinkSmallFontFamily: FdsToken
export const FdsTokenTypographyLinkSmallFontSize: FdsToken
export const FdsTokenTypographyLinkSmallLetterSpacing: FdsToken
export const FdsTokenTypographyLinkSmallLineHeight: FdsToken
export const FdsTokenTypographyLinkSmallFontWeight: FdsToken
export const FdsTokenTypographyLinkSmallTextDecoration: FdsToken
export const FdsTokenTypographyLinkSmallDisplay: FdsToken
export const FdsTokenTypographyLinkDefaultFontFamily: FdsToken
export const FdsTokenTypographyLinkDefaultFontSize: FdsToken
export const FdsTokenTypographyLinkDefaultLetterSpacing: FdsToken
export const FdsTokenTypographyLinkDefaultLineHeight: FdsToken
export const FdsTokenTypographyLinkDefaultFontWeight: FdsToken
export const FdsTokenTypographyLinkDefaultTextDecoration: FdsToken
export const FdsTokenTypographyLinkDefaultDisplay: FdsToken
export const FdsTokenTypographyUiHelperFontFamily: FdsToken
export const FdsTokenTypographyUiHelperFontSize: FdsToken
export const FdsTokenTypographyUiHelperLetterSpacing: FdsToken
export const FdsTokenTypographyUiHelperLineHeight: FdsToken
export const FdsTokenTypographyUiHelperFontWeight: FdsToken
export const FdsTokenTypographyUiHelperDisplay: FdsToken
export const FdsTokenTypographyUiIdFontFamily: FdsToken
export const FdsTokenTypographyUiIdFontSize: FdsToken
export const FdsTokenTypographyUiIdLetterSpacing: FdsToken
export const FdsTokenTypographyUiIdLineHeight: FdsToken
export const FdsTokenTypographyUiIdFontWeight: FdsToken
export const FdsTokenTypographyUiIdDisplay: FdsToken
export const FdsTokenTypographyUiLabelFontFamily: FdsToken
export const FdsTokenTypographyUiLabelFontSize: FdsToken
export const FdsTokenTypographyUiLabelLetterSpacing: FdsToken
export const FdsTokenTypographyUiLabelLineHeight: FdsToken
export const FdsTokenTypographyUiLabelFontWeight: FdsToken
export const FdsTokenTypographyUiLabelDisplay: FdsToken
export const FdsTokenTypographyUiPlaceholderFontFamily: FdsToken
export const FdsTokenTypographyUiPlaceholderFontSize: FdsToken
export const FdsTokenTypographyUiPlaceholderLetterSpacing: FdsToken
export const FdsTokenTypographyUiPlaceholderLineHeight: FdsToken
export const FdsTokenTypographyUiPlaceholderFontWeight: FdsToken
export const FdsTokenTypographyUiPlaceholderDisplay: FdsToken
export const FdsTokenTypographyUiTagFontFamily: FdsToken
export const FdsTokenTypographyUiTagFontSize: FdsToken
export const FdsTokenTypographyUiTagLetterSpacing: FdsToken
export const FdsTokenTypographyUiTagLineHeight: FdsToken
export const FdsTokenTypographyUiTagFontWeight: FdsToken
export const FdsTokenTypographyUiTagDisplay: FdsToken
export const FdsTokenColorBrandBlack: FdsColorToken
export const FdsTokenColorBrandWhite: FdsColorToken
export const FdsTokenColorDanger50: FdsColorToken
export const FdsTokenColorDanger100: FdsColorToken
export const FdsTokenColorDanger200: FdsColorToken
export const FdsTokenColorDanger300: FdsColorToken
export const FdsTokenColorDanger400: FdsColorToken
export const FdsTokenColorInteractive50: FdsColorToken
export const FdsTokenColorInteractive100: FdsColorToken
export const FdsTokenColorInteractive200: FdsColorToken
export const FdsTokenColorInteractive300: FdsColorToken
export const FdsTokenColorInteractive400: FdsColorToken
export const FdsTokenColorNeutral50: FdsColorToken
export const FdsTokenColorNeutral100: FdsColorToken
export const FdsTokenColorNeutral200: FdsColorToken
export const FdsTokenColorNeutral300: FdsColorToken
export const FdsTokenColorNeutral400: FdsColorToken
export const FdsTokenColorSuccess50: FdsColorToken
export const FdsTokenColorSuccess100: FdsColorToken
export const FdsTokenColorSuccess200: FdsColorToken
export const FdsTokenColorSuccess300: FdsColorToken
export const FdsTokenColorSuccess400: FdsColorToken
export const FdsTokenColorText1: FdsColorToken
export const FdsTokenColorText300: FdsColorToken
export const FdsTokenColorText600: FdsColorToken
export const FdsTokenColorText1000: FdsColorToken
export const FdsTokenColorWarning50: FdsColorToken
export const FdsTokenColorWarning100: FdsColorToken
export const FdsTokenColorWarning200: FdsColorToken
export const FdsTokenColorWarning300: FdsColorToken
export const FdsTokenColorWarning400: FdsColorToken