export const FdsTokenSize1 = { name: "fds-size-1", value: "8px" }
export const FdsTokenSize2 = { name: "fds-size-2", value: "16px" }
export const FdsTokenSize21 = { name: "fds-size-21", value: "21px" }
export const FdsTokenSize3 = { name: "fds-size-3", value: "24px" }
export const FdsTokenSize4 = { name: "fds-size-4", value: "32px" }
export const FdsTokenSize6 = { name: "fds-size-6", value: "48px" }
export const FdsTokenSize8 = { name: "fds-size-8", value: "64px" }
export const FdsTokenSize12 = { name: "fds-size-12", value: "96px" }
export const FdsTokenSize16 = { name: "fds-size-16", value: "128px" }
export const FdsTokenSize24 = { name: "fds-size-24", value: "192px" }
export const FdsTokenSize32 = { name: "fds-size-32", value: "256px" }
export const FdsTokenRadiusCompact = { name: "fds-radius-compact", value: "2px" }
export const FdsTokenRadiusNormal = { name: "fds-radius-normal", value: "4px" }
export const FdsTokenRadiusLarge = { name: "fds-radius-large", value: "8px" }
export const FdsTokenRadiusRounded = { name: "fds-radius-rounded", value: "1000px" }
export const FdsTokenStyleElevation100 = { name: "fds-style-elevation-100", value: "0px 1px 2px 0px rgba(0, 0, 0, 0.24), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)" }
export const FdsTokenStyleElevation200 = { name: "fds-style-elevation-200", value: "0px 6px 6px 0px rgba(0, 0, 0, 0.23), 0px 3px 6px 0px rgba(0, 0, 0, 0.16)" }
export const FdsTokenStyleElevation300 = { name: "fds-style-elevation-300", value: "0px 6px 12px 0px rgba(0, 0, 0, 0.23), 0px 20px 20px 0px rgba(0, 0, 0, 0.19)" }
export const FdsTokenStyleElevation400 = { name: "fds-style-elevation-400", value: "0px 20px 20px 0px rgba(0, 0, 0, 0.22), 0px 50px 100px 0px rgba(0, 0, 0, 0.25)" }
export const FdsTokenTypographyBodyDefaultFontFamily = { name: "fds-typography-body-default-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyBodyDefaultFontSize = { name: "fds-typography-body-default-font-size", value: "16px" }
export const FdsTokenTypographyBodyDefaultLetterSpacing = { name: "fds-typography-body-default-letter-spacing", value: "0px" }
export const FdsTokenTypographyBodyDefaultLineHeight = { name: "fds-typography-body-default-line-height", value: "150%" }
export const FdsTokenTypographyBodyDefaultFontWeight = { name: "fds-typography-body-default-font-weight", value: "400" }
export const FdsTokenTypographyBodyDefaultDisplay = { name: "fds-typography-body-default-display", value: "inline-block" }
export const FdsTokenTypographyBodyLargeFontFamily = { name: "fds-typography-body-large-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyBodyLargeFontSize = { name: "fds-typography-body-large-font-size", value: "18px" }
export const FdsTokenTypographyBodyLargeLetterSpacing = { name: "fds-typography-body-large-letter-spacing", value: "0px" }
export const FdsTokenTypographyBodyLargeLineHeight = { name: "fds-typography-body-large-line-height", value: "150%" }
export const FdsTokenTypographyBodyLargeFontWeight = { name: "fds-typography-body-large-font-weight", value: "400" }
export const FdsTokenTypographyBodyLargeDisplay = { name: "fds-typography-body-large-display", value: "inline-block" }
export const FdsTokenTypographyBodyMicroFontFamily = { name: "fds-typography-body-micro-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyBodyMicroFontSize = { name: "fds-typography-body-micro-font-size", value: "12px" }
export const FdsTokenTypographyBodyMicroLetterSpacing = { name: "fds-typography-body-micro-letter-spacing", value: "0px" }
export const FdsTokenTypographyBodyMicroLineHeight = { name: "fds-typography-body-micro-line-height", value: "150%" }
export const FdsTokenTypographyBodyMicroFontWeight = { name: "fds-typography-body-micro-font-weight", value: "400" }
export const FdsTokenTypographyBodyMicroDisplay = { name: "fds-typography-body-micro-display", value: "inline-block" }
export const FdsTokenTypographyBodySmallFontFamily = { name: "fds-typography-body-small-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyBodySmallFontSize = { name: "fds-typography-body-small-font-size", value: "14px" }
export const FdsTokenTypographyBodySmallLetterSpacing = { name: "fds-typography-body-small-letter-spacing", value: "0px" }
export const FdsTokenTypographyBodySmallLineHeight = { name: "fds-typography-body-small-line-height", value: "150%" }
export const FdsTokenTypographyBodySmallFontWeight = { name: "fds-typography-body-small-font-weight", value: "400" }
export const FdsTokenTypographyBodySmallDisplay = { name: "fds-typography-body-small-display", value: "inline-block" }
export const FdsTokenTypographyEmphasisDefaultFontFamily = { name: "fds-typography-emphasis-default-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyEmphasisDefaultFontSize = { name: "fds-typography-emphasis-default-font-size", value: "16px" }
export const FdsTokenTypographyEmphasisDefaultLetterSpacing = { name: "fds-typography-emphasis-default-letter-spacing", value: "0px" }
export const FdsTokenTypographyEmphasisDefaultLineHeight = { name: "fds-typography-emphasis-default-line-height", value: "150%" }
export const FdsTokenTypographyEmphasisDefaultFontWeight = { name: "fds-typography-emphasis-default-font-weight", value: "700" }
export const FdsTokenTypographyEmphasisDefaultDisplay = { name: "fds-typography-emphasis-default-display", value: "inline-block" }
export const FdsTokenTypographyEmphasisLargeFontFamily = { name: "fds-typography-emphasis-large-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyEmphasisLargeFontSize = { name: "fds-typography-emphasis-large-font-size", value: "18px" }
export const FdsTokenTypographyEmphasisLargeLetterSpacing = { name: "fds-typography-emphasis-large-letter-spacing", value: "0px" }
export const FdsTokenTypographyEmphasisLargeLineHeight = { name: "fds-typography-emphasis-large-line-height", value: "150%" }
export const FdsTokenTypographyEmphasisLargeFontWeight = { name: "fds-typography-emphasis-large-font-weight", value: "700" }
export const FdsTokenTypographyEmphasisLargeDisplay = { name: "fds-typography-emphasis-large-display", value: "inline-block" }
export const FdsTokenTypographyEmphasisMicroFontFamily = { name: "fds-typography-emphasis-micro-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyEmphasisMicroFontSize = { name: "fds-typography-emphasis-micro-font-size", value: "12px" }
export const FdsTokenTypographyEmphasisMicroLetterSpacing = { name: "fds-typography-emphasis-micro-letter-spacing", value: "0px" }
export const FdsTokenTypographyEmphasisMicroLineHeight = { name: "fds-typography-emphasis-micro-line-height", value: "150%" }
export const FdsTokenTypographyEmphasisMicroFontWeight = { name: "fds-typography-emphasis-micro-font-weight", value: "700" }
export const FdsTokenTypographyEmphasisMicroDisplay = { name: "fds-typography-emphasis-micro-display", value: "inline-block" }
export const FdsTokenTypographyEmphasisSmallFontFamily = { name: "fds-typography-emphasis-small-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyEmphasisSmallFontSize = { name: "fds-typography-emphasis-small-font-size", value: "14px" }
export const FdsTokenTypographyEmphasisSmallLetterSpacing = { name: "fds-typography-emphasis-small-letter-spacing", value: "0px" }
export const FdsTokenTypographyEmphasisSmallLineHeight = { name: "fds-typography-emphasis-small-line-height", value: "150%" }
export const FdsTokenTypographyEmphasisSmallFontWeight = { name: "fds-typography-emphasis-small-font-weight", value: "700" }
export const FdsTokenTypographyEmphasisSmallDisplay = { name: "fds-typography-emphasis-small-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading3FontFamily = { name: "fds-typography-heading-large-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading3FontSize = { name: "fds-typography-heading-large-heading-3-font-size", value: "40px" }
export const FdsTokenTypographyHeadingLargeHeading3LetterSpacing = { name: "fds-typography-heading-large-heading-3-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading3LineHeight = { name: "fds-typography-heading-large-heading-3-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading3FontWeight = { name: "fds-typography-heading-large-heading-3-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading3Display = { name: "fds-typography-heading-large-heading-3-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading4FontFamily = { name: "fds-typography-heading-large-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading4FontSize = { name: "fds-typography-heading-large-heading-4-font-size", value: "32px" }
export const FdsTokenTypographyHeadingLargeHeading4LetterSpacing = { name: "fds-typography-heading-large-heading-4-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading4LineHeight = { name: "fds-typography-heading-large-heading-4-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading4FontWeight = { name: "fds-typography-heading-large-heading-4-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading4Display = { name: "fds-typography-heading-large-heading-4-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading5FontFamily = { name: "fds-typography-heading-large-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading5FontSize = { name: "fds-typography-heading-large-heading-5-font-size", value: "28px" }
export const FdsTokenTypographyHeadingLargeHeading5LetterSpacing = { name: "fds-typography-heading-large-heading-5-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading5LineHeight = { name: "fds-typography-heading-large-heading-5-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading5FontWeight = { name: "fds-typography-heading-large-heading-5-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading5Display = { name: "fds-typography-heading-large-heading-5-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading6FontFamily = { name: "fds-typography-heading-large-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading6FontSize = { name: "fds-typography-heading-large-heading-6-font-size", value: "20px" }
export const FdsTokenTypographyHeadingLargeHeading6LetterSpacing = { name: "fds-typography-heading-large-heading-6-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading6LineHeight = { name: "fds-typography-heading-large-heading-6-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading6FontWeight = { name: "fds-typography-heading-large-heading-6-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading6Display = { name: "fds-typography-heading-large-heading-6-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading1FontFamily = { name: "fds-typography-heading-large-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading1FontSize = { name: "fds-typography-heading-large-heading-1-font-size", value: "64px" }
export const FdsTokenTypographyHeadingLargeHeading1LetterSpacing = { name: "fds-typography-heading-large-heading-1-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading1LineHeight = { name: "fds-typography-heading-large-heading-1-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading1FontWeight = { name: "fds-typography-heading-large-heading-1-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading1Display = { name: "fds-typography-heading-large-heading-1-display", value: "inline-block" }
export const FdsTokenTypographyHeadingLargeHeading2FontFamily = { name: "fds-typography-heading-large-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingLargeHeading2FontSize = { name: "fds-typography-heading-large-heading-2-font-size", value: "48px" }
export const FdsTokenTypographyHeadingLargeHeading2LetterSpacing = { name: "fds-typography-heading-large-heading-2-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingLargeHeading2LineHeight = { name: "fds-typography-heading-large-heading-2-line-height", value: "110%" }
export const FdsTokenTypographyHeadingLargeHeading2FontWeight = { name: "fds-typography-heading-large-heading-2-font-weight", value: "700" }
export const FdsTokenTypographyHeadingLargeHeading2Display = { name: "fds-typography-heading-large-heading-2-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading1FontFamily = { name: "fds-typography-heading-small-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading1FontSize = { name: "fds-typography-heading-small-heading-1-font-size", value: "42px" }
export const FdsTokenTypographyHeadingSmallHeading1LetterSpacing = { name: "fds-typography-heading-small-heading-1-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading1LineHeight = { name: "fds-typography-heading-small-heading-1-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading1FontWeight = { name: "fds-typography-heading-small-heading-1-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading1Display = { name: "fds-typography-heading-small-heading-1-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading2FontFamily = { name: "fds-typography-heading-small-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading2FontSize = { name: "fds-typography-heading-small-heading-2-font-size", value: "32px" }
export const FdsTokenTypographyHeadingSmallHeading2LetterSpacing = { name: "fds-typography-heading-small-heading-2-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading2LineHeight = { name: "fds-typography-heading-small-heading-2-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading2FontWeight = { name: "fds-typography-heading-small-heading-2-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading2Display = { name: "fds-typography-heading-small-heading-2-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading3FontFamily = { name: "fds-typography-heading-small-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading3FontSize = { name: "fds-typography-heading-small-heading-3-font-size", value: "28px" }
export const FdsTokenTypographyHeadingSmallHeading3LetterSpacing = { name: "fds-typography-heading-small-heading-3-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading3LineHeight = { name: "fds-typography-heading-small-heading-3-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading3FontWeight = { name: "fds-typography-heading-small-heading-3-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading3Display = { name: "fds-typography-heading-small-heading-3-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading4FontFamily = { name: "fds-typography-heading-small-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading4FontSize = { name: "fds-typography-heading-small-heading-4-font-size", value: "24px" }
export const FdsTokenTypographyHeadingSmallHeading4LetterSpacing = { name: "fds-typography-heading-small-heading-4-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading4LineHeight = { name: "fds-typography-heading-small-heading-4-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading4FontWeight = { name: "fds-typography-heading-small-heading-4-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading4Display = { name: "fds-typography-heading-small-heading-4-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading5FontFamily = { name: "fds-typography-heading-small-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading5FontSize = { name: "fds-typography-heading-small-heading-5-font-size", value: "18px" }
export const FdsTokenTypographyHeadingSmallHeading5LetterSpacing = { name: "fds-typography-heading-small-heading-5-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading5LineHeight = { name: "fds-typography-heading-small-heading-5-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading5FontWeight = { name: "fds-typography-heading-small-heading-5-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading5Display = { name: "fds-typography-heading-small-heading-5-display", value: "inline-block" }
export const FdsTokenTypographyHeadingSmallHeading6FontFamily = { name: "fds-typography-heading-small-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyHeadingSmallHeading6FontSize = { name: "fds-typography-heading-small-heading-6-font-size", value: "16px" }
export const FdsTokenTypographyHeadingSmallHeading6LetterSpacing = { name: "fds-typography-heading-small-heading-6-letter-spacing", value: "0px" }
export const FdsTokenTypographyHeadingSmallHeading6LineHeight = { name: "fds-typography-heading-small-heading-6-line-height", value: "110%" }
export const FdsTokenTypographyHeadingSmallHeading6FontWeight = { name: "fds-typography-heading-small-heading-6-font-weight", value: "700" }
export const FdsTokenTypographyHeadingSmallHeading6Display = { name: "fds-typography-heading-small-heading-6-display", value: "inline-block" }
export const FdsTokenTypographyLinkLargeFontFamily = { name: "fds-typography-link-large-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyLinkLargeFontSize = { name: "fds-typography-link-large-font-size", value: "18px" }
export const FdsTokenTypographyLinkLargeLetterSpacing = { name: "fds-typography-link-large-letter-spacing", value: "0px" }
export const FdsTokenTypographyLinkLargeLineHeight = { name: "fds-typography-link-large-line-height", value: "150%" }
export const FdsTokenTypographyLinkLargeFontWeight = { name: "fds-typography-link-large-font-weight", value: "400" }
export const FdsTokenTypographyLinkLargeTextDecoration = { name: "fds-typography-link-large-text-decoration", value: "underline" }
export const FdsTokenTypographyLinkLargeDisplay = { name: "fds-typography-link-large-display", value: "inline-block" }
export const FdsTokenTypographyLinkMicroFontFamily = { name: "fds-typography-link-micro-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyLinkMicroFontSize = { name: "fds-typography-link-micro-font-size", value: "12px" }
export const FdsTokenTypographyLinkMicroLetterSpacing = { name: "fds-typography-link-micro-letter-spacing", value: "0px" }
export const FdsTokenTypographyLinkMicroLineHeight = { name: "fds-typography-link-micro-line-height", value: "150%" }
export const FdsTokenTypographyLinkMicroFontWeight = { name: "fds-typography-link-micro-font-weight", value: "400" }
export const FdsTokenTypographyLinkMicroTextDecoration = { name: "fds-typography-link-micro-text-decoration", value: "underline" }
export const FdsTokenTypographyLinkMicroDisplay = { name: "fds-typography-link-micro-display", value: "inline-block" }
export const FdsTokenTypographyLinkSmallFontFamily = { name: "fds-typography-link-small-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyLinkSmallFontSize = { name: "fds-typography-link-small-font-size", value: "14px" }
export const FdsTokenTypographyLinkSmallLetterSpacing = { name: "fds-typography-link-small-letter-spacing", value: "0px" }
export const FdsTokenTypographyLinkSmallLineHeight = { name: "fds-typography-link-small-line-height", value: "150%" }
export const FdsTokenTypographyLinkSmallFontWeight = { name: "fds-typography-link-small-font-weight", value: "400" }
export const FdsTokenTypographyLinkSmallTextDecoration = { name: "fds-typography-link-small-text-decoration", value: "underline" }
export const FdsTokenTypographyLinkSmallDisplay = { name: "fds-typography-link-small-display", value: "inline-block" }
export const FdsTokenTypographyLinkDefaultFontFamily = { name: "fds-typography-link-default-font-family", value: "'Public Sans'" }
export const FdsTokenTypographyLinkDefaultFontSize = { name: "fds-typography-link-default-font-size", value: "16px" }
export const FdsTokenTypographyLinkDefaultLetterSpacing = { name: "fds-typography-link-default-letter-spacing", value: "0px" }
export const FdsTokenTypographyLinkDefaultLineHeight = { name: "fds-typography-link-default-line-height", value: "150%" }
export const FdsTokenTypographyLinkDefaultFontWeight = { name: "fds-typography-link-default-font-weight", value: "400" }
export const FdsTokenTypographyLinkDefaultTextDecoration = { name: "fds-typography-link-default-text-decoration", value: "underline" }
export const FdsTokenTypographyLinkDefaultDisplay = { name: "fds-typography-link-default-display", value: "inline-block" }
export const FdsTokenTypographyUiHelperFontFamily = { name: "fds-typography-ui-helper-font-family", value: "'Public Sans', 'PublicSans-Regular'" }
export const FdsTokenTypographyUiHelperFontSize = { name: "fds-typography-ui-helper-font-size", value: "15px" }
export const FdsTokenTypographyUiHelperLetterSpacing = { name: "fds-typography-ui-helper-letter-spacing", value: "0px" }
export const FdsTokenTypographyUiHelperLineHeight = { name: "fds-typography-ui-helper-line-height", value: "100%" }
export const FdsTokenTypographyUiHelperFontWeight = { name: "fds-typography-ui-helper-font-weight", value: "400" }
export const FdsTokenTypographyUiHelperDisplay = { name: "fds-typography-ui-helper-display", value: "inline-block" }
export const FdsTokenTypographyUiIdFontFamily = { name: "fds-typography-ui-id-font-family", value: "'Roboto Mono'" }
export const FdsTokenTypographyUiIdFontSize = { name: "fds-typography-ui-id-font-size", value: "13px" }
export const FdsTokenTypographyUiIdLetterSpacing = { name: "fds-typography-ui-id-letter-spacing", value: "0px" }
export const FdsTokenTypographyUiIdLineHeight = { name: "fds-typography-ui-id-line-height", value: "100%" }
export const FdsTokenTypographyUiIdFontWeight = { name: "fds-typography-ui-id-font-weight", value: "700" }
export const FdsTokenTypographyUiIdDisplay = { name: "fds-typography-ui-id-display", value: "inline-block" }
export const FdsTokenTypographyUiLabelFontFamily = { name: "fds-typography-ui-label-font-family", value: "'Public Sans', 'PublicSans-Medium'" }
export const FdsTokenTypographyUiLabelFontSize = { name: "fds-typography-ui-label-font-size", value: "16px" }
export const FdsTokenTypographyUiLabelLetterSpacing = { name: "fds-typography-ui-label-letter-spacing", value: "0px" }
export const FdsTokenTypographyUiLabelLineHeight = { name: "fds-typography-ui-label-line-height", value: "22px" }
export const FdsTokenTypographyUiLabelFontWeight = { name: "fds-typography-ui-label-font-weight", value: "500" }
export const FdsTokenTypographyUiLabelDisplay = { name: "fds-typography-ui-label-display", value: "inline-block" }
export const FdsTokenTypographyUiPlaceholderFontFamily = { name: "fds-typography-ui-placeholder-font-family", value: "'Public Sans', 'PublicSans-Medium'" }
export const FdsTokenTypographyUiPlaceholderFontSize = { name: "fds-typography-ui-placeholder-font-size", value: "16px" }
export const FdsTokenTypographyUiPlaceholderLetterSpacing = { name: "fds-typography-ui-placeholder-letter-spacing", value: "0px" }
export const FdsTokenTypographyUiPlaceholderLineHeight = { name: "fds-typography-ui-placeholder-line-height", value: "100%" }
export const FdsTokenTypographyUiPlaceholderFontWeight = { name: "fds-typography-ui-placeholder-font-weight", value: "500" }
export const FdsTokenTypographyUiPlaceholderDisplay = { name: "fds-typography-ui-placeholder-display", value: "inline-block" }
export const FdsTokenTypographyUiTagFontFamily = { name: "fds-typography-ui-tag-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTokenTypographyUiTagFontSize = { name: "fds-typography-ui-tag-font-size", value: "16px" }
export const FdsTokenTypographyUiTagLetterSpacing = { name: "fds-typography-ui-tag-letter-spacing", value: "0px" }
export const FdsTokenTypographyUiTagLineHeight = { name: "fds-typography-ui-tag-line-height", value: "100%" }
export const FdsTokenTypographyUiTagFontWeight = { name: "fds-typography-ui-tag-font-weight", value: "700" }
export const FdsTokenTypographyUiTagDisplay = { name: "fds-typography-ui-tag-display", value: "inline-block" }
export const FdsTokenColorBrandBlack = { name: "fds-color-brand-black", value: "#000000" }
export const FdsTokenColorBrandWhite = { name: "fds-color-brand-white", value: "#ffffff" }
export const FdsTokenColorDanger50 = { name: "fds-color-danger-50", value: "#FFF0ED" }
export const FdsTokenColorDanger100 = { name: "fds-color-danger-100", value: "#ff9b87" }
export const FdsTokenColorDanger200 = { name: "fds-color-danger-200", value: "#e55636" }
export const FdsTokenColorDanger300 = { name: "fds-color-danger-300", value: "#b40000" }
export const FdsTokenColorDanger400 = { name: "fds-color-danger-400", value: "#720000" }
export const FdsTokenColorInteractive50 = { name: "fds-color-interactive-50", value: "#EFF8FF" }
export const FdsTokenColorInteractive100 = { name: "fds-color-interactive-100", value: "#90cefe" }
export const FdsTokenColorInteractive200 = { name: "fds-color-interactive-200", value: "#1777f8" }
export const FdsTokenColorInteractive300 = { name: "fds-color-interactive-300", value: "#0034ac" }
export const FdsTokenColorInteractive400 = { name: "fds-color-interactive-400", value: "#001c5b" }
export const FdsTokenColorNeutral50 = { name: "fds-color-neutral-50", value: "#F6F6F6" }
export const FdsTokenColorNeutral100 = { name: "fds-color-neutral-100", value: "#cdcdd7" }
export const FdsTokenColorNeutral200 = { name: "fds-color-neutral-200", value: "#9696aa" }
export const FdsTokenColorNeutral300 = { name: "fds-color-neutral-300", value: "#505064" }
export const FdsTokenColorNeutral400 = { name: "fds-color-neutral-400", value: "#2c2c44" }
export const FdsTokenColorSuccess50 = { name: "fds-color-success-50", value: "#EAFFF8" }
export const FdsTokenColorSuccess100 = { name: "fds-color-success-100", value: "#82e8c3" }
export const FdsTokenColorSuccess200 = { name: "fds-color-success-200", value: "#25a794" }
export const FdsTokenColorSuccess300 = { name: "fds-color-success-300", value: "#005f61" }
export const FdsTokenColorSuccess400 = { name: "fds-color-success-400", value: "#004042" }
export const FdsTokenColorText1 = { name: "fds-color-text-1", value: "#ffffff" }
export const FdsTokenColorText300 = { name: "fds-color-text-300", value: "#9696aa" }
export const FdsTokenColorText600 = { name: "fds-color-text-600", value: "#505064" }
export const FdsTokenColorText1000 = { name: "fds-color-text-1000", value: "#000000" }
export const FdsTokenColorWarning50 = { name: "fds-color-warning-50", value: "#FFFADB" }
export const FdsTokenColorWarning100 = { name: "fds-color-warning-100", value: "#ffe37f" }
export const FdsTokenColorWarning200 = { name: "fds-color-warning-200", value: "#eec200" }
export const FdsTokenColorWarning300 = { name: "fds-color-warning-300", value: "#b47324" }
export const FdsTokenColorWarning400 = { name: "fds-color-warning-400", value: "#6c3e05" }
