name: Verify Commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  checks: write  # required by scacap/action-surefire-report
  contents: read  # required by scacap/action-surefire-report

jobs:
  build:
    name: Verify Pull Request
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'RELEASE')"
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout project files
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Vitest unit tests and coverage
        run: npm run coverage

      - name: Run Playwright tests and coverage
        run: npm run test:e2e

      - name: Aggregate all coverage results into nyc-based report
        run: npm run nyc:coverage

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: vitest-coverage
          path: src/test/coverage/
          retention-days: 30

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ github.actor != 'dependabot[bot]' }} # GHA doesn't expose tokens to PRs from forks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
