name: Verify Commit
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: read

jobs:
  build:
    name: Verify Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project files
        uses: actions/checkout@v4

      - name: Check if Actor is a Member of one of the teams
        uses: im-open/is-actor-team-member@v1.2.0
        with:
          github-actor: ${{ github.actor }}
          github-organization: tmfg
          github-team-slugs: |
            ["digitraffic-tis-solita"]
          github-usernames: |
            ["dependabot[bot]"]
          github-token: ${{ secrets.ORG_MEMBER_READ }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Vitest unit tests and coverage
        run: npm run coverage

      - name: Run Playwright tests and coverage
        run: npm run test:e2e

      - name: Aggregate all coverage results into nyc-based report
        run: npm run nyc:coverage

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: aggregated-coverage
          path: coverage/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-source
          path: src/test/coverage/
          retention-days: 30

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ github.actor != 'dependabot[bot]' }} # GHA doesn't expose tokens to PRs from forks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
