name: Verify Commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write  # required by scacap/action-surefire-report
  contents: read  # required by scacap/action-surefire-report

jobs:
  build:
    name: Verify Pull Request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout project files
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
