name: "Build and push to ECR"
on:
  workflow_run:
    workflows: [ "Release new version" ]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndPushImageToECR:
    needs: build
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project files (pull request version)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout project files (push version)
        uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1
          role-duration-seconds: 7200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract the latest version
        id: latestversion
        run: |
          echo "LATESTVERSION=$(git log --format=%B -n1 | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "digitraffic-tis-ui"
          IMAGE_TAG: ${{ steps.latestversion.outputs.LATESTVERSION }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
