name: "Build and push to ECR"
on:
  push:
    branches:
      - main
  #workflow_run:
  #  workflows: [ "Release new version" ]
  #  types:
  #    - completed

permissions:
  id-token: write
  contents: write

#env:
#  commitmessage: $(git log --format=%B -n1 | awk '{print $1}')

jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'RELEASE')"

    steps:
      - name: Checkout project files (pull request version)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout project files (push version)
        uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1
          role-duration-seconds: 7200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract latest commit message
        id: commitmessage
        run: |
          echo "MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
          echo "Commit message: ${{ steps.commitmessage.outputs.MESSAGE }} / ${{ github.event.head_commit.message }}"

      - name: Extract the latest version
        id: latestversion
        env:
          version: ${{ github.event.head_commit.message }} | cut -d' ' -f2
        run: |
          echo "LATESTVERSION=$(echo ${{ github.event.head_commit.message }} | cut -d' ' -f2)" >> $GITHUB_OUTPUT
       #   { echo -n "LATESTVERSION=" && echo ${{ github.event.head_commit.message }} | cut -d' ' -f2 } >>  $GITHUB_OUTPUT
        #echo "Latest version: ${{ steps.latestversion.outputs.LATESTVERSION }}"
        #echo "Test: $( env.MESSAGE | awk '{print $2}') / $( ${{ env.MESSAGE }} | awk '{print $2}') / ${{ env.MESSAGE }} / ${{ env.MESSAGE | awk '{print $2} }} / ${{ $(env.MESSAGE | awk '{print $2}) }} "
         #echo "Latest version: ${{ steps.latestversion.outputs.LATESTVERSION }} / ${{ github.event.head_commit.message }} / $(github.event.head_commit.message | awk '{print $2}')" / $(${{github.event.head_commit.message}} | awk '{print $2}')" "

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "digitraffic-tis-ui"
          IMAGE_TAG: ${{ steps.latestversion.outputs.LATESTVERSION }}
        run: |
          echo "Ta-da!! Version: ${{ steps.latestversion.outputs.LATESTVERSION }}"
          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
